
spring:
  application:
    name: Api Gateway Microservice
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: localhost:9411
  cloud:
    gateway:
      default-filters:

      routes:
        - id: produto
          uri: http://localhost:8082
          predicates:
            - Path=/produto/**
        - id: cliente
          uri: http://localhost:8081
          predicates:
            -  Path=/cliente/**
        - id: pedido
          uri: http://localhost:8083
          predicates:
            - Path=/pedido/**

server:
  port: 8090


